version: '3'

services:
  web:
    restart: always
    build:
      context: ../..
      dockerfile: ./docker/dev/web/Dockerfile
    expose:
      - 8181

  nginx:
    restart: always
    image: nginx:latest
    ports:
      - "8081:8081"
    depends_on:
      - web
    links:
      - web:web
    volumes:
      - ./nginx/sites-enabled:/etc/nginx/conf.d
      - ../../webroms/static_root:/opt/webroms/static_root
