# Generated by Django 2.1.2 on 2018-11-02 21:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dishes', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, default=1.0, max_digits=100, verbose_name='Количество')),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dishes.Dish', verbose_name='Набор блюд')),
            ],
            options={
                'ordering': ['-updated'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', 'Создан'), ('paid', 'Оплачен'), ('delivered', 'Заказ доставлен'), ('canceled', 'Отменен')], max_length=11, verbose_name='Статус заказа')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания заказа')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата обновления заказа')),
                ('dishes', models.ManyToManyField(to='restaurants.DishItem', verbose_name='Набор блюд к заказу')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Employee', verbose_name='Сотрудник (оператор)')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Ресторан')),
                ('address', models.CharField(max_length=256, verbose_name='Адрес')),
                ('city', models.CharField(max_length=256, verbose_name='Город')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.Restaurant', verbose_name='Ресторан'),
        ),
        migrations.AlterUniqueTogether(
            name='dishitem',
            unique_together={('dish', 'total')},
        ),
    ]
